import { Entity, Column, Index, CreateDateColumn, ManyToOne, JoinColumn } from 'typeorm';
import { BaseEntity } from './base.entity';
import { User } from './user.entity';
import { Tenant } from './tenant.entity';

export enum AdminAuditAction {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  SUSPEND = 'suspend',
  ACTIVATE = 'activate',
  CHANGE_PLAN = 'change_plan',
  ENABLE_FEATURE = 'enable_feature',
  DISABLE_FEATURE = 'disable_feature',
  RESET_PASSWORD = 'reset_password',
  FORCE_MFA = 'force_mfa',
  DISABLE_MFA = 'disable_mfa',
  ASSIGN_ROLE = 'assign_role',
  REVOKE_ROLE = 'revoke_role',
  EXPORT = 'export',
  IMPORT = 'import',
  BACKUP = 'backup',
  RESTORE = 'restore',
  CONFIGURE = 'configure',
}

export enum AdminAuditEntityType {
  ORGANIZATION = 'organization',
  TENANT = 'tenant',
  USER = 'user',
  LICENSE = 'license',
  SUBSCRIPTION = 'subscription',
  DEPLOYMENT = 'deployment',
  SYSTEM_SETTING = 'system_setting',
  COMPLIANCE_EVIDENCE = 'compliance_evidence',
  AUDIT_LOG = 'audit_log',
  SYSTEM_ADMIN = 'system_admin',
}

/**
 * Immutable audit log for all system admin actions
 * Required for compliance and security investigations
 *
 * Access: System admins only
 * Retention: Indefinite (archive-only after 7 years)
 * Integrity: No updates/deletes, only inserts
 */
@Entity('admin_audit_log')
@Index('idx_admin_audit_admin_time', ['adminUserId', 'createdAt'])
@Index('idx_admin_audit_tenant_action_time', ['tenantId', 'action', 'createdAt'])
@Index('idx_admin_audit_entity_time', ['entityType', 'entityId', 'createdAt'])
@Index('idx_admin_audit_action_time', ['action', 'createdAt'])
@Index('idx_admin_audit_time', ['createdAt'])
export class AdminAuditLog extends BaseEntity {
  @Column({ type: 'uuid', name: 'admin_user_id', nullable: true })
  adminUserId?: string;

  @ManyToOne(() => User, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'admin_user_id' })
  adminUser?: User;

  @Column({ type: 'uuid', name: 'tenant_id', nullable: true })
  tenantId?: string;

  @ManyToOne(() => Tenant, { nullable: true, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'tenant_id' })
  tenant?: Tenant;

  @Column({
    type: 'enum',
    enum: AdminAuditAction,
    name: 'action',
  })
  action: AdminAuditAction;

  @Column({
    type: 'enum',
    enum: AdminAuditEntityType,
    name: 'entity_type',
  })
  entityType: AdminAuditEntityType;

  @Column({ type: 'uuid', name: 'entity_id', nullable: true })
  entityId?: string;

  @Column({ type: 'varchar', length: 255, name: 'entity_label', nullable: true })
  entityLabel?: string; // Human-readable entity name (e.g., org name, user email)

  @Column({ type: 'varchar', length: 500, nullable: true })
  description?: string; // Human-readable description of what changed

  @Column({ type: 'jsonb', nullable: true, name: 'old_values' })
  oldValues?: Record<string, any>; // Before state (only for UPDATE/DELETE)

  @Column({ type: 'jsonb', nullable: true, name: 'new_values' })
  newValues?: Record<string, any>; // After state (only for UPDATE/CREATE)

  @Column({ type: 'varchar', length: 50, nullable: true, name: 'ip_address' })
  ipAddress?: string; // Admin's IP address

  @Column({ type: 'varchar', length: 255, nullable: true, name: 'user_agent' })
  userAgent?: string; // Admin's browser/client

  @Column({ type: 'varchar', length: 255, nullable: true, name: 'change_reason' })
  changeReason?: string; // Why was this change made (ticket #, policy, etc.)

  @Column({ type: 'boolean', default: false, name: 'system_generated' })
  systemGenerated: boolean; // Whether this was auto-generated by system (migrations, etc.)

  @Column({ type: 'varchar', length: 50, default: 'success', name: 'result' })
  result: 'success' | 'failure' | 'partial'; // Outcome of the action

  @Column({ type: 'text', nullable: true, name: 'error_message' })
  errorMessage?: string; // If result = failure, what went wrong

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  // Archive fields (7+ year retention)
  @Column({ type: 'boolean', default: false, name: 'is_archived' })
  isArchived: boolean;

  @Column({ type: 'timestamp', nullable: true, name: 'archived_at' })
  archivedAt?: Date;

  @Column({ type: 'varchar', length: 255, nullable: true, name: 'archive_location' })
  archiveLocation?: string; // S3 path, cold storage, etc.

  @Column({ type: 'varchar', length: 64, nullable: true })
  hash?: string;

  @Column({ name: 'previous_hash', type: 'varchar', length: 64, nullable: true })
  previousHash?: string;
}
